### ISSUE TITLE
World Crashes when attempting to access the user inventory on local server

### ISSUE THREAD

**Issue by KinreeveNaku** [IHOC/Server#11]
TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods): Sky Factory 3 Custom (version 3.1)

Narrative description of issue or crash:
World I have had since your earliest postings of the modpack crashes consistently upon attempting to access the users local inventory in version (3.1). No particularly unique conditions required to replicate the scenario besides having a world constructed from within a prior modpack build

Steps to reproduce the issue or crash:
start world up and access personal inventory via any means in world created via prior version of the modpack

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com): http://pastebin.com/2vHf8Gw2

Link to console logs (posted on http://gist.github.com):
https://gist.github.com/KinreeveNaku/75769b025af4f6f86f0b13833f906b17

OS of Client computer: Windows 8.1

Version of JAVA on Client: Version 8 Update 111 (build 1.8.0_111-b14)

Version of Minecraft: 1.10.2

Version of Forge:
net.minecraftforge:forge:1.10.2-12.18.3.2239
List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):
https://gist.github.com/KinreeveNaku/57efe6c143e710ae45d7e27ce79d8bdd

**Comment by Gunner76th** [comment]
This is a known issue that has already been reported to NEI and JEI and the mod authors have already issued updates to address the issue. This problem is been resolved with update 3.2 on the technic launcher. Please update your pack to version 3.2

**Comment by McAzzaMan** [comment]
Issue still occurring in 3.2, updated through technic. Clean install has the same problem. Opening inventory crashes game.

**Comment by Gunner76th** [comment]
We are aware and have issued a new bug report to the mod author.
